<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilitySeeder extends Seeder
{
    public function run()
    {
        DB::table('facility')->insert([
            [
                'facility_id' => 1,
                'name' => 'Tokyo Tower',
                'location' => 'Tokyo',
                'latitude' => 35.6586,
                'longitude' => 139.7454,
                'price' => 1000,
                'openinghours' => '09:00-22:00',
            ],
            [
                'facility_id' => 2,
                'name' => 'Osaka Castle',
                'location' => 'Osaka',
                'latitude' => 34.6873,
                'longitude' => 135.5259,
                'price' => 600,
                'openinghours' => '09:00-17:00',
            ],
            [
                'facility_id' => 3,
                'name' => 'Fukuoka Tower',
                'location' => 'Fukuoka',
                'latitude' => 33.5931,
                'longitude' => 130.3519,
                'price' => 800,
                'openinghours' => '10:00-20:00',
            ],
            [
                'facility_id' => 4,
                'name' => '東京おもちゃ美術館',
                'location' => 'Tokyo',
                'latitude' => 35.6878333,
                'longitude' => 139.6999597,
                'price' => 1300,
                'openinghours' => '10:00-16:00',
            ],
            [
                'facility_id' => 5,
                'name' => 'まんだらけ 中野店',
                'location' => 'Tokyo',
                'latitude' => 35.7089732,
                'longitude' => 139.6631579,
                'price' => 0,
                'openinghours' => '12:00-20:00',
            ],
            [
                'facility_id' => 6,
                'name' => '浅草寺',
                'location' => '東京都台東区浅草2-3-1',
                'latitude' => 35.7148,
                'longitude' => 139.7967,
                'price' => 0,
                'openinghours' => '6:00-17:00',
            ],
            [
                'facility_id' => 7,
                'name' => 'スカイツリー',
                'location' => '東京都墨田区押上1-1-2',
                'latitude' => 35.7101,
                'longitude' => 139.8107,
                'price' => 2100,
                'openinghours' => '10:00-21:00',
            ],
            [
                'facility_id' => 8,
                'name' => '上野動物園',
                'location' => '東京都台東区上野公園9-83',
                'latitude' => 35.7151,
                'longitude' => 139.7711,
                'price' => 600,
                'openinghours' => '9:30-17:00',
            ],
            [
                'facility_id' => 9,
                'name' => '明治神宮',
                'location' => '東京都渋谷区代々木神園町1-1',
                'latitude' => 35.6764,
                'longitude' => 139.6993,
                'price' => 0,
                'openinghours' => '5:00-18:00',
            ],
            [
                'facility_id' => 10,
                'name' => '新宿御苑',
                'location' => '東京都新宿区内藤町11',
                'latitude' => 35.6852,
                'longitude' => 139.7101,
                'price' => 500,
                'openinghours' => '9:00-16:30',
            ],
            [
                'facility_id' => 11,
                'name' => '渋谷スクランブル交差点',
                'location' => '東京都渋谷区道玄坂2丁目',
                'latitude' => 35.6595,
                'longitude' => 139.7005,
                'price' => 0,
                'openinghours' => '24時間',
            ],
            [
                'facility_id' => 12,
                'name' => '秋葉原電気街',
                'location' => '東京都千代田区外神田1丁目',
                'latitude' => 35.6983,
                'longitude' => 139.7730,
                'price' => 0,
                'openinghours' => '10:00-20:00',
            ],
            [
                'facility_id' => 13,
                'name' => 'お台場海浜公園',
                'location' => '東京都港区台場1丁目',
                'latitude' => 35.6290,
                'longitude' => 139.7745,
                'price' => 0,
                'openinghours' => '24時間',
            ],
            [
                'facility_id' => 14,
                'name' => '豊洲市場',
                'location' => '東京都江東区豊洲6-6-1',
                'latitude' => 35.6427,
                'longitude' => 139.7857,
                'price' => 0,
                'openinghours' => '5:00-17:00',
            ],
            [
                'facility_id' => 15,
                'name' => '皇居',
                'location' => '東京都千代田区千代田１−１',
                'latitude' => 35.6851793,
                'longitude' => 139.7502246,
                'price' => 0,
                'openinghours' => '9:00-15:00',
            ],
            [
                'facility_id' => 16,
                'name' => '六本木ヒルズ',
                'location' => '東京都港区六本木６丁目１０−１',
                'latitude' => 35.6607397,
                'longitude' => 139.7247258,
                'price' => 0,
                'openinghours' => '11:00-23:00',
            ],
            [
                'facility_id' => 17,
                'name' => '銀座',
                'location' => '東京都中央区',
                'latitude' => 35.6696431,
                'longitude' => 139.7552393,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 18,
                'name' => '築地場外市場',
                'location' => '東京都中央区築地４丁目',
                'latitude' => 35.6650799,
                'longitude' => 139.768096,
                'price' => 0,
                'openinghours' => '9:00-14:00',
            ],
            [
                'facility_id' => 19,
                'name' => '竹下通り',
                'location' => '東京都渋谷区神宮前１丁目',
                'latitude' => 35.6710378,
                'longitude' => 139.7026072,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 20,
                'name' => '代々木公園',
                'location' => '東京都渋谷区代々木神園町２−１',
                'latitude' => 35.6700692,
                'longitude' => 139.6923907,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 21,
                'name' => '東京ドームシティ',
                'location' => '東京都文京区後楽１丁目３−６１',
                'latitude' => 35.7044711,
                'longitude' => 139.7503709,
                'price' => 0,
                'openinghours' => '11:00-21:00',
            ],
            [
                'facility_id' => 22,
                'name' => '三鷹の森ジブリ美術館',
                'location' => '東京都三鷹市下連雀１丁目１−８３',
                'latitude' => 35.6962423,
                'longitude' => 139.5678568,
                'price' => 1000,
                'openinghours' => '10:00-18:00',
            ],
            [
                'facility_id' => 23,
                'name' => '目黒川の桜並木',
                'location' => '東京都目黒区目黒',
                'latitude' => 35.6358828,
                'longitude' => 139.70598,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 24,
                'name' => '東京国立博物館',
                'location' => '東京都台東区上野公園１３−９',
                'latitude' => 35.7188394,
                'longitude' => 139.7739466,
                'price' => 1000,
                'openinghours' => '9:30-17:00',
            ],
            [
                'facility_id' => 25,
                'name' => '国立新美術館',
                'location' => '東京都港区六本木７丁目２２−２',
                'latitude' => 35.6652933,
                'longitude' => 139.7237991,
                'price' => 1500,
                'openinghours' => '10:00-18:00',
            ],
            [
                'facility_id' => 26,
                'name' => '池袋サンシャインシティ',
                'location' => '東京都豊島区東池袋３丁目１',
                'latitude' => 35.7289081,
                'longitude' => 139.7182421,
                'price' => 0,
                'openinghours' => '10:00-20:00',
            ],
            [
                'facility_id' => 27,
                'name' => '東京ミッドタウン',
                'location' => '東京都港区赤坂９丁目７−１',
                'latitude' => 35.6659803,
                'longitude' => 139.7128503,
                'price' => 0,
                'openinghours' => '11:00-23:00',
            ],
            [
                'facility_id' => 28,
                'name' => 'レインボーブリッジ',
                'location' => '東京都港区',
                'latitude' => 35.6372174,
                'longitude' => 139.7585499,
                'price' => 0,
                'openinghours' => '10:00-18:00',
            ],
            [
                'facility_id' => 29,
                'name' => '神田明神',
                'location' => '東京都千代田区外神田２丁目１６−２',
                'latitude' => 35.7020186,
                'longitude' => 139.7633882,
                'price' => 0,
                'openinghours' => '9:00-18:00',
            ],
            [
                'facility_id' => 30,
                'name' => '高尾山',
                'location' => '東京都八王子市高尾町',
                'latitude' => 35.6254452,
                'longitude' => 139.2231388,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 31,
                'name' => '上野恩賜公園',
                'location' => '東京都台東区上野公園',
                'latitude' => 35.7147557,
                'longitude' => 139.7689251,
                'price' => 0,
                'openinghours' => '5:00-23:00',
            ],
            [
                'facility_id' => 32,
                'name' => '東京都庁展望室',
                'location' => '東京都新宿区西新宿２丁目８−１ 東京都庁第一本庁舎 45F',
                'latitude' => 35.6895333,
                'longitude' => 139.6891597,
                'price' => 0,
                'openinghours' => '9:30-22:00',
            ],
            [
                'facility_id' => 33,
                'name' => '日比谷公園',
                'location' => '東京都千代田区日比谷公園１−６',
                'latitude' => 35.6736115,
                'longitude' => 139.7468647,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 34,
                'name' => '新宿ゴールデン街',
                'location' => '東京都新宿区歌舞伎町',
                'latitude' => 35.6941161,
                'longitude' => 139.7021862,
                'price' => 0,
                'openinghours' => '24/7',
            ],
            [
                'facility_id' => 35,
                'name' => 'エスパス日拓新宿歌舞伎町店',
                'location' => '東京都新宿区歌舞伎町１丁目２３−３',
                'latitude' => 35.6940757,
                'longitude' => 139.6982015,
                'price' => 10000,
                'openinghours' => '10:00-22:45',
            ],
        ]);
    }
}
